* PostgreSQL karaf feature

This is a maven pom that generates an apache karaf feature repository with a feature loading and setarting the PostgreSQL JDBC driver and all its dependencies.

[[https://maven-badges.herokuapp.com/maven-central/no.priv.bang.karaf/postgresql-jdbc-karaf][file:https://maven-badges.herokuapp.com/maven-central/no.priv.bang.karaf/postgresql-jdbc-karaf/badge.svg]]

** Installing the feature in karaf

Give the following commands from the karaf console:
#+BEGIN_EXAMPLE
  feature:repo-add mvn:no.priv.bang.karaf/postgresql-jdbc-karaf/LATEST/xml/features
  feature:install postgresql-jdbc-karaf
#+END_EXAMPLE

** Use the feature in a maven project

If you have a maven project building an OSGi bundle with a karaf feature repository attached, using the [[https://svn.apache.org/repos/asf/karaf/site/production/manual/latest/karaf-maven-plugin.html#_using_the_karaf_maven_plugin][karaf-maven-plugin]], then you can add a runtime dependency to this feature by adding the following to the maven dependencies of your project:
#+BEGIN_SRC xml
  <dependency>
      <groupId>no.priv.bang.karaf</groupId>
      <artifactId>postgresql-jdbc-karaf</artifactId>
      <version>1.2.0</version>
      <type>xml</type>
      <classifier>features</classifier>
  </dependency>
#+END_SRC

** Release history

It might simplify things if I'm able give the feature the same version number as the PGJDBC driver the feature pulls in an starts.  But for the moment the version numbers are different.

| Release | PostgreSQL JDBC version | Comment                                                                                                        |
|---------+-------------------------+----------------------------------------------------------------------------------------------------------------|
|   1.2.0 |                  42.2.6 | Depend on karaf built-in feature transaction-api instead of loading and starting bundles the pgjdbc depends on |
|   1.1.0 |                  42.2.6 | PostgreSQL JDBC driver that survives OSGi bundle reload                                                        |
|   1.0.1 |                  42.2.5 |                                                                                                                |

** License

The license is the same [[https://jdbc.postgresql.org/about/license.html][simplified BSD-2 license as the PostgreSQL driver itself]].

See the LICENSE file for details.
